// Minerva — opportunity → Dynatrace notebook document (M6).
//
// Turns a ranked Opportunity into a notebook the user can keep: a markdown section that states the
// finding, quantified impact (with its assumption), effort/confidence/dissent, and the recommended
// action; followed by one DQL section per piece of evidence that carries a query — so the notebook
// is self-proving (every claim links to a re-runnable query). Structure per the dt-app-notebooks
// skill (type "notebook", content.version "7", ordered `sections`).

import type { Opportunity, StartObjectiveRequest, Verdict } from '../contract.js';

export interface NotebookSection {
  id: string;
  type: 'markdown' | 'dql';
  title?: string;
  markdown?: string;
  showInput?: boolean;
  state?: {
    input: { value: string };
    visualization: string;
    visualizationSettings: { autoSelectVisualization: boolean; chartSettings: Record<string, unknown> };
    querySettings: {
      maxResultRecords: number;
      defaultScanLimitGbytes: number;
      maxResultMegaBytes: number;
      defaultSamplingRatio: number;
      enableSampling: boolean;
    };
  };
}

export interface NotebookDoc {
  name: string;
  type: 'notebook';
  content: {
    version: '7';
    defaultTimeframe: { from: string; to: string };
    sections: NotebookSection[];
  };
}

// Deterministic ids keep the document stable across rebuilds (and tests). Not the platform id —
// that's assigned on create.
const sectionId = (oppId: string, suffix: string) => `minerva-${oppId}-${suffix}`;

const QUERY_SETTINGS = {
  maxResultRecords: 1000,
  defaultScanLimitGbytes: 500,
  maxResultMegaBytes: 1,
  defaultSamplingRatio: 10,
  enableSampling: false,
};

function dqlSection(oppId: string, idx: number, title: string, dql: string): NotebookSection {
  return {
    id: sectionId(oppId, `q${idx}`),
    type: 'dql',
    title,
    showInput: true,
    state: {
      input: { value: dql },
      visualization: 'table',
      visualizationSettings: { autoSelectVisualization: true, chartSettings: {} },
      querySettings: QUERY_SETTINGS,
    },
  };
}

/** A human-readable arrow, e.g. "4.2 → 1.5 s (−64%)". */
function impactLine(o: Opportunity): string {
  const { before, after, unit } = o.impact;
  const pct = before !== 0 ? Math.round(((after - before) / before) * 100) : 0;
  const sign = pct > 0 ? '+' : '';
  return `**${before} → ${after} ${unit}** (${sign}${pct}%)`;
}

/** Build the notebook document for one opportunity. */
export function buildNotebook(
  opportunity: Opportunity,
  objective: StartObjectiveRequest,
  environment: string,
): NotebookDoc {
  const o = opportunity;

  const evidenceList = o.evidence
    .map((e) => `- **[${e.source}]** ${e.label} — ${e.resultSummary} _(confidence: ${e.confidence})_`)
    .join('\n');

  const markdown = [
    `# ${o.finding}`,
    ``,
    `_Minerva opportunity for objective: **${objective.kind}** — ${objective.statement}_`,
    ``,
    `## Impact`,
    `${impactLine(o)} on ${o.impact.metric}.`,
    `**Assumption:** ${o.impact.assumption}`,
    ``,
    `## Assessment`,
    `- **Effort:** ${o.effort}`,
    `- **Confidence:** ${o.confidence} — ${o.confidenceReason}`,
    o.dissent ? `- **Dissent:** ${o.dissent}` : `- **Dissent:** none`,
    ``,
    `## Recommended action`,
    o.recommendedAction,
    ``,
    `## Evidence`,
    evidenceList || '_No evidence captured._',
    ``,
    `---`,
    `_Generated by Minerva from ${environment}. Each query below is re-runnable._`,
  ].join('\n');

  const sections: NotebookSection[] = [
    { id: sectionId(o.id, 'md'), type: 'markdown', markdown },
  ];

  o.evidence.forEach((e, i) => {
    if (e.dql) sections.push(dqlSection(o.id, i + 1, e.label, e.dql));
  });

  return {
    name: `Minerva — ${o.finding}`.slice(0, 120),
    type: 'notebook',
    content: {
      version: '7',
      defaultTimeframe: { from: 'now()-2h', to: 'now()' },
      sections,
    },
  };
}

/** Title-case stance label for the verdict heading, e.g. "Refuted". */
const STANCE_LABEL: Record<Verdict['stance'], string> = {
  confirmed: 'Confirmed',
  refuted: 'Refuted',
  inconclusive: 'Inconclusive',
};

/** A human-readable arrow for a verdict's impact, e.g. "4.2 → 4.1 s (−2%)". */
function verdictImpactLine(impact: NonNullable<Verdict['impact']>): string {
  const { before, after, unit } = impact;
  const pct = before !== 0 ? Math.round(((after - before) / before) * 100) : 0;
  const sign = pct > 0 ? '+' : '';
  return `**${before} → ${after} ${unit}** (${sign}${pct}%)`;
}

/** Build the notebook document for one verdict (validation mode). */
export function buildVerdictNotebook(
  verdict: Verdict,
  objective: StartObjectiveRequest,
  environment: string,
): NotebookDoc {
  const v = verdict;

  const evidenceList = v.evidence
    .map((e) => `- **[${e.source}]** ${e.label} — ${e.resultSummary} _(confidence: ${e.confidence})_`)
    .join('\n');

  const impactLines = v.impact
    ? [
        `${verdictImpactLine(v.impact)} on ${v.impact.metric}.`,
        `**Assumption:** ${v.impact.assumption}`,
        v.whySmall ? `**Why small:** ${v.whySmall}` : '',
      ].filter(Boolean)
    : ['Impact — not projectable from telemetry.'];

  const markdown = [
    `# ${STANCE_LABEL[v.stance]}: ${v.claim}`,
    ``,
    `_Minerva verdict for objective: **${objective.kind}** — ${objective.statement}_`,
    `_Scope: ${v.service} ${v.endpoint}_`,
    ``,
    `## Impact`,
    ...impactLines,
    ``,
    `## Assessment`,
    `- **Confidence:** ${v.confidence} — ${v.confidenceReason}`,
    v.dissent ? `- **Dissent:** ${v.dissent}` : `- **Dissent:** none`,
    ``,
    `## Recommended action`,
    v.recommendedAction,
    ...(v.redirect
      ? [
          ``,
          `## What actually matters`,
          v.redirect.finding,
          `**Projected:** ${v.redirect.deltaLine}`,
        ]
      : []),
    ``,
    `## Evidence`,
    evidenceList || '_No evidence captured._',
    ``,
    `---`,
    `_Generated by Minerva from ${environment}. Each query below is re-runnable._`,
  ].join('\n');

  const sections: NotebookSection[] = [
    { id: sectionId(v.id, 'md'), type: 'markdown', markdown },
  ];

  v.evidence.forEach((e, i) => {
    if (e.dql) sections.push(dqlSection(v.id, i + 1, e.label, e.dql));
  });

  return {
    name: `Minerva — ${STANCE_LABEL[v.stance]}: ${v.claim}`.slice(0, 120),
    type: 'notebook',
    content: {
      version: '7',
      defaultTimeframe: { from: 'now()-2h', to: 'now()' },
      sections,
    },
  };
}
